name: Build and Push Docker Image

on:
  workflow_dispatch:  # Manual trigger
  push:
    paths:
      - 'Dockerfile.working'
      - '.github/workflows/build-docker-image.yml'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}/builder

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        tags: |
          type=raw,value=latest
          type=raw,value=ubuntu22.04-nightly-2024-05-01
          type=sha
    
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile.working
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
    
    - name: Summary
      run: |
        cat >> $GITHUB_STEP_SUMMARY << EOF
        # ðŸ³ Docker Image Built and Pushed
        
        **Registry:** ${{ env.REGISTRY }}
        **Image:** ${{ env.IMAGE_NAME }}
        
        ## Available Tags
        
        $(echo '${{ steps.meta.outputs.tags }}' | sed 's/^/- /')
        
        ## Usage in Other Workflows
        
        \`\`\`yaml
        jobs:
          build:
            runs-on: ubuntu-latest
            container:
              image: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
        \`\`\`
        
        ## Pull Command
        
        \`\`\`bash
        docker pull ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
        \`\`\`
        EOF