- name: Generate Cargo.lock with current stable Rust
  shell: bash
  run: |
    set -euxo pipefail
    rustup toolchain install stable --profile minimal
    cargo +stable generate-lockfile

- name: Verify with the build toolchain
  shell: bash
  run: |
    set -euxo pipefail
    rustup toolchain install nightly-2024-05-01 --profile minimal
    cargo +nightly-2024-05-01 metadata --locked --format-version 1 --no-deps
    cargo +nightly-2024-05-01 fetch --locked
